## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN','NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
threshold = 200
apps_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < threshold].index.tolist()

# Replace in dataframe
for app in apps_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_more_than_one = classification_counts[classification_counts > 1]
classifications_more_than_one

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 1000
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() <= cutoff].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [10]:
#turn booleans into binary

booleans = application_df_dummies.select_dtypes(include=['bool']).columns
application_df_dummies[booleans] = application_df_dummies[booleans].astype('int64')
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [18]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies['IS_SUCCESSFUL']  # Target variable
X = application_df_dummies.drop('IS_SUCCESSFUL', axis=1)  # Features

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)  

y_train = y_train.values.reshape(-1, 1)  # Reshape to (n_samples, 1)
y_test = y_test.values.reshape(-1, 1)    # Reshape to (n_samples, 1)

In [19]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model using the best Keras Tuner models and now optimizing using gradient ascent

In [ ]:

# Define your model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(71, activation='relu', input_dim=X_train.shape[1]),  # Use the number of features in X_train
    tf.keras.layers.Dense(11, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Output layer for binary classification
])

c:\ProgramData\anaconda3\envs\my-env\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 71)             │         3,124 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 11)             │           792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 6)              │           102 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 11)             │            77 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,299 (16.79 KB)

 Trainable params: 4,299 (16.79 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# Gradient Ascent parameters
learning_rate = 0.01
epochs = 100

In [24]:
# Create an optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

In [25]:
# Custom training loop for Gradient Ascent
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        # Forward pass
        predictions = model(X_train, training=True)
        # Compute loss
        loss = tf.keras.losses.binary_crossentropy(y_train, predictions)
        # Compute accuracy
        accuracy = tf.keras.metrics.binary_accuracy(y_train, predictions)

    # Compute gradients (negative because we want to maximize)
    gradients = tape.gradient(loss, model.trainable_variables)
    
    # Apply gradients using the optimizer
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    # Print loss and accuracy
    print(f'Epoch {epoch + 1}, Loss: {tf.reduce_mean(loss).numpy()}, Accuracy: {tf.reduce_mean(accuracy).numpy()}')

# After training, you can evaluate the model
model.evaluate(X_test, y_test)

Epoch 1, Loss: 11115.4931640625, Accuracy: 0.5321489572525024
Epoch 2, Loss: 2077.239501953125, Accuracy: 0.46785104274749756
Epoch 3, Loss: 89.16761779785156, Accuracy: 0.46785104274749756
Epoch 4, Loss: 2848.935546875, Accuracy: 0.5321489572525024
Epoch 5, Loss: 2901.408447265625, Accuracy: 0.5321489572525024
Epoch 6, Loss: 1300.7493896484375, Accuracy: 0.5321489572525024
Epoch 7, Loss: 1323.305419921875, Accuracy: 0.46785104274749756
Epoch 8, Loss: 1743.3453369140625, Accuracy: 0.46785104274749756
Epoch 9, Loss: 1722.82666015625, Accuracy: 0.46785104274749756
Epoch 10, Loss: 1279.2423095703125, Accuracy: 0.46785104274749756
Epoch 11, Loss: 382.97021484375, Accuracy: 0.46785104274749756
Epoch 12, Loss: 639.039794921875, Accuracy: 0.5321489572525024
Epoch 13, Loss: 987.54931640625, Accuracy: 0.5321489572525024
Epoch 14, Loss: 820.0185546875, Accuracy: 0.5321489572525024
Epoch 15, Loss: 330.0828857421875, Accuracy: 0.5321489572525024
Epoch 16, Loss: 258.02264404296875, Accuracy: 0.46785104274749756
Epoch 17, Loss: 498.31488037109375, Accuracy: 0.46785104274749756
Epoch 18, Loss: 546.4105224609375, Accuracy: 0.46785104274749756
Epoch 19, Loss: 464.3977966308594, Accuracy: 0.46785104274749756
Epoch 20, Loss: 310.29632568359375, Accuracy: 0.46785104274749756
Epoch 21, Loss: 133.71031188964844, Accuracy: 0.46785104274749756
Epoch 22, Loss: 41.37261962890625, Accuracy: 0.5321489572525024
Epoch 23, Loss: 125.9648208618164, Accuracy: 0.5321489572525024
Epoch 24, Loss: 132.5718231201172, Accuracy: 0.5321489572525024
Epoch 25, Loss: 100.18231964111328, Accuracy: 0.5321489572525024
Epoch 26, Loss: 56.72890090942383, Accuracy: 0.5321489572525024
Epoch 27, Loss: 20.895309448242188, Accuracy: 0.5321489572525024
Epoch 28, Loss: 2.2864763736724854, Accuracy: 0.5321489572525024
Epoch 29, Loss: 0.6921640038490295, Accuracy: 0.5321489572525024
Epoch 30, Loss: 44.50273132324219, Accuracy: 0.46785104274749756
Epoch 31, Loss: 0.692127525806427, Accuracy: 0.5321489572525024
Epoch 32, Loss: 0.6920989751815796, Accuracy: 0.5321489572525024
Epoch 33, Loss: 0.6920697093009949, Accuracy: 0.5321489572525024
Epoch 34, Loss: 0.6920406818389893, Accuracy: 0.5321489572525024
Epoch 35, Loss: 0.6920115351676941, Accuracy: 0.5321489572525024
Epoch 36, Loss: 0.6919819116592407, Accuracy: 0.5321489572525024
Epoch 37, Loss: 0.6919533610343933, Accuracy: 0.5321489572525024
Epoch 38, Loss: 0.691925585269928, Accuracy: 0.5321489572525024
Epoch 39, Loss: 0.6918951272964478, Accuracy: 0.5321489572525024
Epoch 40, Loss: 0.6918672919273376, Accuracy: 0.5321489572525024
Epoch 41, Loss: 0.6918385624885559, Accuracy: 0.5321489572525024
Epoch 42, Loss: 0.6918096542358398, Accuracy: 0.5321489572525024
Epoch 43, Loss: 0.6917808651924133, Accuracy: 0.5321489572525024
Epoch 44, Loss: 0.6917527914047241, Accuracy: 0.5321489572525024
Epoch 45, Loss: 0.6917234063148499, Accuracy: 0.5321489572525024
Epoch 46, Loss: 0.6916952133178711, Accuracy: 0.5321489572525024
Epoch 47, Loss: 0.6916688680648804, Accuracy: 0.5321489572525024
Epoch 48, Loss: 0.6916585564613342, Accuracy: 0.5321489572525024
Epoch 49, Loss: 0.6916482448577881, Accuracy: 0.5321489572525024
Epoch 50, Loss: 0.6916313767433167, Accuracy: 0.5321489572525024
Epoch 51, Loss: 0.6916095614433289, Accuracy: 0.5321489572525024
Epoch 52, Loss: 0.6915822625160217, Accuracy: 0.5321489572525024
Epoch 53, Loss: 0.6915543675422668, Accuracy: 0.5321489572525024
Epoch 54, Loss: 0.691540539264679, Accuracy: 0.5321489572525024
Epoch 55, Loss: 0.691527247428894, Accuracy: 0.5321489572525024
Epoch 56, Loss: 0.6915157437324524, Accuracy: 0.5321489572525024
Epoch 57, Loss: 0.6915013790130615, Accuracy: 0.5321489572525024
Epoch 58, Loss: 0.6914861798286438, Accuracy: 0.5321489572525024
Epoch 59, Loss: 0.6914717555046082, Accuracy: 0.5321489572525024
Epoch 60, Loss: 0.6914564967155457, Accuracy: 0.5321489572525024
Epoch 61, Loss: 0.69144207239151, Accuracy: 0.5321489572525024
Epoch 62, Loss: 0.6914264559745789, Accuracy: 0.5321489572525024
Epoch 63, Loss: 0.6914118528366089, Accuracy: 0.5321489572525024
Epoch 64, Loss: 0.6913966536521912, Accuracy: 0.5321489572525024
Epoch 65, Loss: 0.691382884979248, Accuracy: 0.5321489572525024
Epoch 66, Loss: 0.6913666725158691, Accuracy: 0.5321489572525024
Epoch 67, Loss: 0.6913517117500305, Accuracy: 0.5321489572525024
Epoch 68, Loss: 0.6913372278213501, Accuracy: 0.5321489572525024
Epoch 69, Loss: 0.6913236975669861, Accuracy: 0.5321489572525024
Epoch 70, Loss: 0.6913137435913086, Accuracy: 0.5321489572525024
Epoch 71, Loss: 0.6913051009178162, Accuracy: 0.5321489572525024
Epoch 72, Loss: 0.6912913918495178, Accuracy: 0.5321489572525024
Epoch 73, Loss: 0.6912794709205627, Accuracy: 0.5321489572525024
Epoch 74, Loss: 0.6912682056427002, Accuracy: 0.5321489572525024
Epoch 75, Loss: 0.6912590265274048, Accuracy: 0.5321489572525024
Epoch 76, Loss: 0.691251277923584, Accuracy: 0.5321489572525024
Epoch 77, Loss: 0.6912431120872498, Accuracy: 0.5321489572525024
Epoch 78, Loss: 0.6912346482276917, Accuracy: 0.5321489572525024
Epoch 79, Loss: 0.6912246942520142, Accuracy: 0.5321489572525024
Epoch 80, Loss: 0.691216766834259, Accuracy: 0.5321489572525024
Epoch 81, Loss: 0.6912082433700562, Accuracy: 0.5321489572525024
Epoch 82, Loss: 0.6912009716033936, Accuracy: 0.5321489572525024
Epoch 83, Loss: 0.6911922097206116, Accuracy: 0.5321489572525024
Epoch 84, Loss: 0.6911842226982117, Accuracy: 0.5321489572525024
Epoch 85, Loss: 0.6911775469779968, Accuracy: 0.5321489572525024
Epoch 86, Loss: 0.6911725401878357, Accuracy: 0.5321489572525024
Epoch 87, Loss: 0.691166341304779, Accuracy: 0.5321489572525024
Epoch 88, Loss: 0.6911589503288269, Accuracy: 0.5321489572525024
Epoch 89, Loss: 0.691154956817627, Accuracy: 0.5321489572525024
Epoch 90, Loss: 0.6911489367485046, Accuracy: 0.5321489572525024
Epoch 91, Loss: 0.6911448836326599, Accuracy: 0.5321489572525024
Epoch 92, Loss: 0.6911397576332092, Accuracy: 0.5321489572525024
Epoch 93, Loss: 0.6911359429359436, Accuracy: 0.5321489572525024
Epoch 94, Loss: 0.6911311149597168, Accuracy: 0.5321489572525024
Epoch 95, Loss: 0.6911264061927795, Accuracy: 0.5321489572525024
Epoch 96, Loss: 0.69112229347229, Accuracy: 0.5321489572525024
Epoch 97, Loss: 0.6911184787750244, Accuracy: 0.5321489572525024
Epoch 98, Loss: 0.6911153793334961, Accuracy: 0.5321489572525024
Epoch 99, Loss: 0.6911121010780334, Accuracy: 0.5321489572525024
Epoch 100, Loss: 0.6911078691482544, Accuracy: 0.5321489572525024
268/268 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.5262 - loss: 0.6918

[0.6909899115562439, 0.5331778526306152]

In [26]:
# Train the model
# Fit the model to the training data
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.5286 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5347 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5326 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5300 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5319 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5308 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5327 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5294 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5339 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5320 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5317 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5320 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5316 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5399 - loss: 0.6901 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5333 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5316 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5302 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5326 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5277 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5338 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5306 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5321 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5359 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5348 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5361 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5342 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5330 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5342 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5311 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5343 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5351 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5312 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5299 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5308 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5306 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5336 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5301 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5300 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5270 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5294 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5270 - loss: 0.6918 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5319 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5324 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5347 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5313 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5230 - loss: 0.6922 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5328 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5301 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5319 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5272 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5375 - loss: 0.6904 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5288 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5311 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5333 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5289 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5311 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5333 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5377 - loss: 0.6904 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5334 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5336 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5342 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5349 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5363 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5272 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5374 - loss: 0.6904 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5328 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5282 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5250 - loss: 0.6920 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5308 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5338 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5294 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5282 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5291 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5336 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5328 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5347 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5344 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5292 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5286 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5358 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5265 - loss: 0.6918 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5383 - loss: 0.6903 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5329 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5393 - loss: 0.6901 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5329 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5365 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5340 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5355 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5355 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5365 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5319 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910

In [27]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.5320 - loss: 0.6906
Loss: 0.6905847191810608, Accuracy: 0.5320116877555847

In [28]:
# Export our model to HDF5 file
model_filename = 'AlphabetSoupCharity_Optimized2.h5'  # Specify the filename for the model
model.save(model_filename)  # Save the model

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.