## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN','NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
threshold = 200
apps_to_replace = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() < threshold].index.tolist()

# Replace in dataframe
for app in apps_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_more_than_one = classification_counts[classification_counts > 1]
classifications_more_than_one

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 1000
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() <= cutoff].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [10]:
#turn booleans into binary

booleans = application_df_dummies.select_dtypes(include=['bool']).columns
application_df_dummies[booleans] = application_df_dummies[booleans].astype('int64')
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies['IS_SUCCESSFUL']  # Target variable
X = application_df_dummies.drop('IS_SUCCESSFUL', axis=1)  # Features

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

USE KERAS TUNER

In [28]:
# Create a method that creates a new Sequential model with hyperparameter options
def make_model(hp):
    nn = tf.keras.models.Sequential()

    input_dim = len(X_train_scaled[0])

    # Allow kerastuner to decide which activation function to use in hidden layers
    activate = hp.Choice('activation',['relu','tanh'])

    # Allow kerastuner to decide number of neurons in first layer
    nn.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=80,
        step=5), activation=activate, input_dim=input_dim))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 5)):
        nn.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=40,
            step=5),
            activation=activate))

    nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

    return nn

In [14]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    make_model,
    objective="val_accuracy",
    max_epochs=20,
    hyperband_iterations=2)

Reloading Tuner from .\untitled_project\tuner0.json

In [ ]:
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

In [16]:
# Evaluate the top 3 models against the test dataset
top_model = tuner.get_best_models(3)
for model in top_model:
    model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
    print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

WARNING:tensorflow:From c:\ProgramData\anaconda3\envs\my-env\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

c:\ProgramData\anaconda3\envs\my-env\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\ProgramData\anaconda3\envs\my-env\Lib\site-packages\keras\src\saving\saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 30 variables.
  saveable.load_own_variables(weights_store.get(inner_path))
c:\ProgramData\anaconda3\envs\my-env\Lib\site-packages\keras\src\saving\saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

268/268 - 1s - 2ms/step - accuracy: 0.7298 - loss: 0.5505
Loss: 0.5505225658416748, Accuracy: 0.7297959327697754
268/268 - 0s - 2ms/step - accuracy: 0.7296 - loss: 0.5556
Loss: 0.5555818676948547, Accuracy: 0.7295626997947693
268/268 - 0s - 2ms/step - accuracy: 0.7293 - loss: 0.5504
Loss: 0.5504138469696045, Accuracy: 0.7293294668197632

In [17]:
top_model_hyper = tuner.get_best_hyperparameters(1)[0]
top_model_hyper.values

{'activation': 'relu',
 'first_units': 71,
 'num_layers': 5,
 'units_0': 11,
 'units_1': 16,
 'units_2': 6,
 'units_3': 11,
 'units_4': 1,
 'tuner/epochs': 20,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 0,
 'tuner/round': 0}

## Compile, Train and Evaluate the Model using the best Keras Tuner models

In [24]:


# Initialize the Model
model = tf.keras.models.Sequential()

# Add the first hidden layer with specified units and activation function
model.add(tf.keras.layers.Dense(units=71, activation='relu', input_dim=43))  # Assuming input_dim=2 for a 2D input

# Add additional hidden layers based on the specified units
model.add(tf.keras.layers.Dense(units=11, activation='relu'))  # units_0
model.add(tf.keras.layers.Dense(units=16, activation='relu'))  # units_1
model.add(tf.keras.layers.Dense(units=6, activation='relu'))   # units_2
model.add(tf.keras.layers.Dense(units=11, activation='relu'))  # units_3
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # units_4 (output layer for binary classification)


# Display the model's architecture
model.summary()

c:\ProgramData\anaconda3\envs\my-env\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_17 (Dense)                │ (None, 71)             │         3,124 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 11)             │           792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 16)             │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 6)              │           102 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 11)             │            77 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,299 (16.79 KB)

 Trainable params: 4,299 (16.79 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
# Train the model
# Fit the model to the training data
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.4977 - loss: 2604.0417 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5301 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5312 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5282 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5349 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5289 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5328 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5309 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5333 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5313 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5318 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5320 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5344 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5368 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5328 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5309 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5318 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5279 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5296 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5327 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5360 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5291 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5337 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5323 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5324 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5346 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5312 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5310 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5292 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5309 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5311 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5340 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5335 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5345 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5279 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5327 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5324 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5319 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5321 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5288 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5341 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5330 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5308 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5295 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5282 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5330 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5265 - loss: 0.6918 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5319 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5300 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5320 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5325 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5286 - loss: 0.6916 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5292 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5308 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5374 - loss: 0.6904 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5288 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5308 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5369 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5291 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5265 - loss: 0.6918 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5338 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5308 - loss: 0.6913 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5365 - loss: 0.6905 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5352 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5365 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5329 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5315 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5330 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5311 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5261 - loss: 0.6919 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5351 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5293 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5341 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5358 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5354 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5358 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5316 - loss: 0.6912 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5328 - loss: 0.6910 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5318 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5351 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5289 - loss: 0.6915 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5346 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5323 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5323 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5338 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5382 - loss: 0.6903 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5354 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5357 - loss: 0.6907 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5349 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5343 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5276 - loss: 0.6917 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5335 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5339 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5299 - loss: 0.6914 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5357 - loss: 0.6906 - val_accuracy: 0.5332 - val_loss: 0.6910
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5349 - loss: 0.6908 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5341 - loss: 0.6909 - val_accuracy: 0.5332 - val_loss: 0.6909
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5320 - loss: 0.6911 - val_accuracy: 0.5332 - val_loss: 0.6909

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.4668 - loss: 2.7401
Loss: 2.7400963306427, Accuracy: 0.46682214736938477

In [17]:
# Export our model to HDF5 file
model_filename = 'AlphabetSoupCharity_Optimized2.h5'  # Specify the filename for the model
model.save(model_filename)  # Save the model

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.